-- Rowshan Moving Company Invoice Module Upgrade (v9)
-- Run ONCE in Supabase SQL Editor on the existing Rowshan Moving Company project.

create extension if not exists pgcrypto;

alter table public.invoices drop constraint if exists invoices_booking_id_key;
alter table public.invoices alter column booking_id drop not null;

alter table public.invoices add column if not exists public_token text;
alter table public.invoices add column if not exists client_name text;
alter table public.invoices add column if not exists client_email text;
alter table public.invoices add column if not exists client_phone text;
alter table public.invoices add column if not exists invoice_date date default current_date;
alter table public.invoices add column if not exists subtotal numeric(10,2);
alter table public.invoices add column if not exists gst_rate numeric(5,2) default 5.00;
alter table public.invoices add column if not exists gst_amount numeric(10,2);
alter table public.invoices add column if not exists total_amount numeric(10,2);

update public.invoices
set public_token = coalesce(public_token, encode(gen_random_bytes(18),'hex')),
    invoice_date = coalesce(invoice_date, issued_at::date),
    total_amount = coalesce(total_amount, final_amount),
    subtotal = coalesce(subtotal, round(final_amount / 1.05, 2)),
    gst_rate = coalesce(gst_rate, 5.00),
    gst_amount = coalesce(gst_amount, final_amount - round(final_amount / 1.05, 2))
where public_token is null or total_amount is null or subtotal is null or gst_amount is null;

alter table public.invoices alter column public_token set default encode(gen_random_bytes(18),'hex');
alter table public.invoices alter column public_token set not null;
create unique index if not exists invoices_public_token_unique on public.invoices(public_token);

create table if not exists public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  description text not null,
  qty numeric(10,2) not null default 1 check(qty > 0),
  unit text not null default 'hour',
  unit_rate numeric(10,2) not null default 0 check(unit_rate >= 0),
  line_total numeric(10,2) not null default 0 check(line_total >= 0),
  sort_order integer not null default 100
);

alter table public.invoice_items enable row level security;
drop policy if exists "admins invoice_items" on public.invoice_items;
create policy "admins invoice_items" on public.invoice_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
grant select,insert,update,delete on public.invoice_items to authenticated;
grant usage,select on all sequences in schema public to authenticated;

create or replace function public.get_public_invoice_by_token(p_token text)
returns jsonb
language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'invoice_number', i.invoice_number,
    'invoice_date', i.invoice_date,
    'due_date', i.due_date,
    'status', i.status,
    'client_name', coalesce(i.client_name, trim(coalesce(b.first_name,'') || ' ' || coalesce(b.last_name,''))),
    'client_email', coalesce(i.client_email,b.email),
    'client_phone', coalesce(i.client_phone,b.phone),
    'booking_reference', b.reference,
    'service_date', b.service_date,
    'origin', b.origin,
    'destination', b.destination,
    'subtotal', coalesce(i.subtotal, i.final_amount),
    'gst_rate', coalesce(i.gst_rate,0),
    'gst_amount', coalesce(i.gst_amount,0),
    'total_amount', coalesce(i.total_amount,i.final_amount),
    'final_amount', coalesce(i.total_amount,i.final_amount),
    'note', i.note,
    'public_token', i.public_token,
    'items', coalesce((
      select jsonb_agg(jsonb_build_object(
        'description',ii.description,
        'qty',ii.qty,
        'unit',ii.unit,
        'unit_rate',ii.unit_rate,
        'line_total',ii.line_total
      ) order by ii.sort_order,ii.id)
      from public.invoice_items ii where ii.invoice_id=i.id
    ), '[]'::jsonb)
  )
  from public.invoices i
  left join public.bookings b on b.id=i.booking_id
  where i.public_token=p_token
  limit 1;
$$;

grant execute on function public.get_public_invoice_by_token(text) to anon,authenticated;
