-- Rowshan Moving Company production schema (Supabase/Postgres)
-- Run once in Supabase SQL Editor on a NEW Rowshan Moving Company project.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id integer primary key default 1 check (id=1),
  gst_rate numeric(5,2) not null default 5.00,
  business_hours text not null default '8:00 AM–8:00 PM',
  booking_slots text[] not null default array['8:00 AM','9:00 AM','10:00 AM','11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM','6:00 PM'],
  timezone text not null default 'America/Edmonton',
  updated_at timestamptz not null default now()
);
insert into public.settings(id) values (1) on conflict (id) do nothing;

create table if not exists public.services (
  id text primary key,
  name text not null,
  category text not null,
  description text not null,
  price numeric(10,2) not null check (price >= 0),
  unit text not null default 'hour',
  minimum numeric(8,2) not null default 2 check (minimum > 0),
  image text not null,
  active boolean not null default true,
  sort_order integer not null default 100,
  updated_at timestamptz not null default now()
);

insert into public.services(id,name,category,description,price,unit,minimum,image,active,sort_order) values
('labour','1 Person Labour / Assembly','Labour','Loading help, furniture assembly, packing, organizing and on-site moving support.',50,'hour',2,'assets/rowshan-moving-sofa.jpg',true,10),
('pickup','1 Mover + Pickup / Small Delivery','Delivery','Pickup truck service for Marketplace, IKEA, small moves, deliveries and light dump runs. Fuel included within Calgary.',75,'hour',2,'assets/rowshan-moving-truck-team.jpg',true,20),
('truck2','2 Movers + Moving Box Truck','Moving','Professional two-person crew with box truck. Includes blankets, straps, shrink wrap, tape and dolly.',135,'hour',2,'assets/service-box-truck.webp',true,30),
('helper','Additional Helper','Add-on','Extra labour for heavy or oversized items such as pianos, treadmills, pool tables and saunas.',50,'helper/hour',2,'assets/service-heavy-moving.webp',true,40),
('junk','Dump Run / Junk Removal','Junk Removal','Pickup, loading and disposal support. Landfill charges are added from the official receipt.',75,'hour',2,'assets/service-junk-removal.webp',true,50),
('packing','Packing & Unpacking Support','Packing','Careful packing, unpacking and organization assistance before or after your move.',50,'hour',2,'assets/service-packing.webp',true,60)
on conflict (id) do update set name=excluded.name,category=excluded.category,description=excluded.description,price=excluded.price,unit=excluded.unit,minimum=excluded.minimum,image=excluded.image,sort_order=excluded.sort_order;

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  reference text not null unique,
  first_name text not null,
  last_name text not null,
  phone text not null,
  email text not null,
  service_date date not null,
  start_slot text not null,
  origin text not null,
  destination text not null,
  details text,
  subtotal numeric(10,2) not null,
  gst_amount numeric(10,2) not null,
  total_estimate numeric(10,2) not null,
  status text not null default 'Confirmed',
  job_status text not null default 'Scheduled',
  invoice_status text not null default 'Not Issued',
  payment_status text not null default 'Not Required Yet',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create unique index if not exists bookings_active_slot_unique on public.bookings(service_date,start_slot) where lower(status) <> 'cancelled';

create table if not exists public.booking_items (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete cascade,
  service_id text references public.services(id),
  service_name text not null,
  qty numeric(8,2) not null,
  unit_price numeric(10,2) not null,
  unit text not null,
  line_total numeric(10,2) not null
);

create table if not exists public.availability_blocks (
  id bigint generated by default as identity primary key,
  block_date date not null,
  start_slot text,
  reason text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists availability_blocks_date_idx on public.availability_blocks(block_date);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  google_review_id text unique,
  author text not null,
  rating integer not null check (rating between 1 and 5),
  review_text text not null,
  review_date date,
  source text not null default 'Google',
  source_url text,
  visible boolean not null default true,
  sort_order integer not null default 100,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number text not null unique,
  booking_id uuid references public.bookings(id) on delete set null,
  public_token text not null unique default encode(gen_random_bytes(18),'hex'),
  client_name text,
  client_email text,
  client_phone text,
  invoice_date date not null default current_date,
  subtotal numeric(10,2),
  gst_rate numeric(5,2) not null default 5.00,
  gst_amount numeric(10,2),
  total_amount numeric(10,2),
  final_amount numeric(10,2) not null check(final_amount > 0),
  status text not null default 'Draft',
  note text,
  issued_at timestamptz not null default now(),
  due_date date,
  updated_at timestamptz not null default now()
);

create table if not exists public.invoice_items (
  id bigint generated by default as identity primary key,
  invoice_id uuid not null references public.invoices(id) on delete cascade,
  description text not null,
  qty numeric(10,2) not null default 1 check(qty > 0),
  unit text not null default 'hour',
  unit_rate numeric(10,2) not null default 0 check(unit_rate >= 0),
  line_total numeric(10,2) not null default 0 check(line_total >= 0),
  sort_order integer not null default 100
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.admin_users where user_id=auth.uid());
$$;

create or replace function public.get_public_day_availability(p_date date)
returns table(slot_label text,state text)
language sql stable security definer set search_path=public as $$
  with slots as (
    select unnest(coalesce((select booking_slots from public.settings where id=1), array['8:00 AM','9:00 AM','10:00 AM','11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM','6:00 PM'])) as slot_label
  )
  select s.slot_label,
    case
      when exists(select 1 from public.bookings b where b.service_date=p_date and b.start_slot=s.slot_label and lower(b.status)<>'cancelled') then 'booked'
      when exists(select 1 from public.availability_blocks a where a.block_date=p_date and a.active and (a.start_slot is null or a.start_slot=s.slot_label)) then 'unavailable'
      else 'available'
    end as state
  from slots s;
$$;

create or replace function public.create_public_booking(
  p_first_name text,
  p_last_name text,
  p_phone text,
  p_email text,
  p_service_date date,
  p_start_slot text,
  p_origin text,
  p_destination text,
  p_details text,
  p_items jsonb
)
returns table(booking_reference text,subtotal numeric,gst_amount numeric,total_estimate numeric)
language plpgsql security definer set search_path=public as $$
declare
  v_id uuid;
  v_ref text;
  v_subtotal numeric(10,2);
  v_gst_rate numeric(5,2);
  v_gst numeric(10,2);
  v_total numeric(10,2);
  v_count integer;
begin
  if p_service_date < current_date then raise exception 'INVALID_DATE'; end if;
  if not exists(select 1 from unnest((select booking_slots from public.settings where id=1)) x where x=p_start_slot) then raise exception 'INVALID_SLOT'; end if;
  if exists(select 1 from public.availability_blocks a where a.block_date=p_service_date and a.active and (a.start_slot is null or a.start_slot=p_start_slot)) then raise exception 'SLOT_BLOCKED'; end if;
  if exists(select 1 from public.bookings b where b.service_date=p_service_date and b.start_slot=p_start_slot and lower(b.status)<>'cancelled') then raise exception 'SLOT_UNAVAILABLE'; end if;

  with requested as (
    select x.service_id, greatest(x.qty, s.minimum) qty, s.name, s.price, s.unit
    from jsonb_to_recordset(coalesce(p_items,'[]'::jsonb)) as x(service_id text, qty numeric)
    join public.services s on s.id=x.service_id and s.active=true
  )
  select count(*),coalesce(sum(qty*price),0) into v_count,v_subtotal from requested;
  if v_count=0 or v_subtotal<=0 then raise exception 'NO_VALID_SERVICES'; end if;

  select gst_rate into v_gst_rate from public.settings where id=1;
  v_gst=round(v_subtotal*(coalesce(v_gst_rate,5)/100),2); v_total=v_subtotal+v_gst;
  v_ref='RB-'||to_char(p_service_date,'YYYYMMDD')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,6));

  begin
    insert into public.bookings(reference,first_name,last_name,phone,email,service_date,start_slot,origin,destination,details,subtotal,gst_amount,total_estimate)
    values(v_ref,trim(p_first_name),trim(p_last_name),trim(p_phone),lower(trim(p_email)),p_service_date,p_start_slot,trim(p_origin),trim(p_destination),nullif(trim(p_details),''),v_subtotal,v_gst,v_total)
    returning id into v_id;
  exception when unique_violation then
    raise exception 'SLOT_UNAVAILABLE';
  end;

  insert into public.booking_items(booking_id,service_id,service_name,qty,unit_price,unit,line_total)
  select v_id,s.id,s.name,greatest(x.qty,s.minimum),s.price,s.unit,round(greatest(x.qty,s.minimum)*s.price,2)
  from jsonb_to_recordset(p_items) as x(service_id text, qty numeric)
  join public.services s on s.id=x.service_id and s.active=true;

  return query select v_ref,v_subtotal,v_gst,v_total;
end;
$$;

create or replace function public.get_public_invoice(p_invoice_number text)
returns table(invoice_number text,booking_reference text,final_amount numeric,status text)
language sql stable security definer set search_path=public as $$
 select i.invoice_number,b.reference,i.final_amount,i.status from public.invoices i join public.bookings b on b.id=i.booking_id where i.invoice_number=p_invoice_number limit 1;
$$;

create or replace function public.get_public_invoice_by_token(p_token text)
returns jsonb
language sql stable security definer set search_path=public as $$
  select jsonb_build_object(
    'invoice_number', i.invoice_number,
    'invoice_date', i.invoice_date,
    'due_date', i.due_date,
    'status', i.status,
    'client_name', coalesce(i.client_name, trim(coalesce(b.first_name,'') || ' ' || coalesce(b.last_name,''))),
    'client_email', coalesce(i.client_email,b.email),
    'client_phone', coalesce(i.client_phone,b.phone),
    'booking_reference', b.reference,
    'service_date', b.service_date,
    'origin', b.origin,
    'destination', b.destination,
    'subtotal', coalesce(i.subtotal, i.final_amount),
    'gst_rate', coalesce(i.gst_rate,0),
    'gst_amount', coalesce(i.gst_amount,0),
    'total_amount', coalesce(i.total_amount,i.final_amount),
    'final_amount', coalesce(i.total_amount,i.final_amount),
    'note', i.note,
    'public_token', i.public_token,
    'items', coalesce((select jsonb_agg(jsonb_build_object('description',ii.description,'qty',ii.qty,'unit',ii.unit,'unit_rate',ii.unit_rate,'line_total',ii.line_total) order by ii.sort_order,ii.id) from public.invoice_items ii where ii.invoice_id=i.id),'[]'::jsonb)
  ) from public.invoices i left join public.bookings b on b.id=i.booking_id where i.public_token=p_token limit 1;
$$;


alter table public.admin_users enable row level security;
alter table public.settings enable row level security;
alter table public.services enable row level security;
alter table public.bookings enable row level security;
alter table public.booking_items enable row level security;
alter table public.availability_blocks enable row level security;
alter table public.reviews enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;

-- Public data: only active services, visible reviews, and safe settings.
create policy "public active services" on public.services for select to anon using (active=true);
create policy "public visible reviews" on public.reviews for select to anon using (visible=true);
create policy "public settings read" on public.settings for select to anon using (id=1);

-- Admin access, protected by Supabase Auth + admin_users membership.
create policy "admins admin_users" on public.admin_users for select to authenticated using (public.is_admin());
create policy "admins settings" on public.settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins services" on public.services for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins bookings" on public.bookings for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins booking_items" on public.booking_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins availability" on public.availability_blocks for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins reviews" on public.reviews for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins invoices" on public.invoices for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "admins invoice_items" on public.invoice_items for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- Explicit grants; RLS policies still apply.
grant select on public.services,public.reviews,public.settings to anon;
grant select,insert,update,delete on public.admin_users,public.settings,public.services,public.bookings,public.booking_items,public.availability_blocks,public.reviews,public.invoices,public.invoice_items to authenticated;
grant usage,select on all sequences in schema public to authenticated;
grant execute on function public.get_public_day_availability(date) to anon,authenticated;
grant execute on function public.create_public_booking(text,text,text,text,date,text,text,text,text,jsonb) to anon,authenticated;
grant execute on function public.get_public_invoice(text) to anon,authenticated;
grant execute on function public.get_public_invoice_by_token(text) to anon,authenticated;
grant execute on function public.is_admin() to authenticated;

-- Optional: enable Realtime for admin dashboards if desired later.
-- alter publication supabase_realtime add table public.bookings, public.availability_blocks;
