(function(){
const form=document.getElementById('bookingForm'); if(!form)return;
const list=document.getElementById('bookingServiceList'),summary=document.getElementById('bookingSummary'),dateEl=document.getElementById('bookingDate'),slots=document.getElementById('timeSlots'),timeInput=document.getElementById('bookingTime'),msg=document.getElementById('bookingMsg');
const selected=new Map();let services=[];let settings={gst_rate:5};let refreshTimer=null;
function setMsg(text,type=''){msg.textContent=text||'';msg.className='note'+(type?` ${type}`:'')}
function renderServices(){list.innerHTML=services.filter(s=>s.active!==false).map(s=>`<div class="booking-service-option"><label class="service-choice"><input type="checkbox" data-service="${s.id}"><span><strong>${RMC.escapeHtml(s.name)}</strong><small>${RMC.escapeHtml(s.description)}</small><b>${RMC.money(s.price)} / ${RMC.escapeHtml(s.unit)}</b></span></label><label class="service-hours">Hours<input type="number" data-hours="${s.id}" min="${s.minimum||1}" step="0.5" value="${s.minimum||1}" disabled></label></div>`).join('');
const q=document.getElementById('quoteServiceList');if(q){q.innerHTML=(RMC.quoteServices||[]).map(name=>`<a class="quote-service-link" href="contact.html?service=${encodeURIComponent(name)}"><span>${RMC.escapeHtml(name)}</span><strong>Request a Quote →</strong></a>`).join('');}
list.querySelectorAll('[data-service]').forEach(c=>c.onchange=()=>{const s=services.find(x=>x.id===c.dataset.service),h=list.querySelector(`[data-hours="${s.id}"]`);h.disabled=!c.checked;if(c.checked)selected.set(s.id,{id:s.id,service_id:s.id,name:s.name,price:Number(s.price),unit:s.unit,qty:Number(h.value)});else selected.delete(s.id);sync();});
list.querySelectorAll('[data-hours]').forEach(h=>h.oninput=()=>{if(selected.has(h.dataset.hours)){const x=selected.get(h.dataset.hours);x.qty=Math.max(Number(h.value)||1,Number(h.min)||1);selected.set(h.dataset.hours,x);sync();}});
}
function sync(){const items=[...selected.values()];if(!items.length){summary.innerHTML='<p class="muted-light">No services selected yet.</p>';return}const t=RMC.totals(items,Number(settings.gst_rate||5));summary.innerHTML=items.map(i=>`<div class="cart-line"><div><strong>${RMC.escapeHtml(i.name)}</strong><br><small>${i.qty} × ${RMC.money(i.price)} / ${RMC.escapeHtml(i.unit)}</small></div><strong>${RMC.money(i.qty*i.price)}</strong></div>`).join('')+`<div class="cart-line"><span>Subtotal</span><strong>${RMC.money(t.subtotal)}</strong></div><div class="cart-line"><span>GST ${t.gstRate}%</span><strong>${RMC.money(t.gst)}</strong></div><div class="cart-total"><span>Estimated total</span><strong>${RMC.money(t.total)}</strong></div>`;}
const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());dateEl.min=now.toISOString().split('T')[0];const requestedDate=new URLSearchParams(location.search).get('date');if(requestedDate&&requestedDate>=dateEl.min)dateEl.value=requestedDate;
async function getAvailability(d){
 if(!RMCData.configured()) return ['8:00 AM','9:00 AM','10:00 AM','11:00 AM','12:00 PM','1:00 PM','2:00 PM','3:00 PM','4:00 PM','5:00 PM','6:00 PM'].map(slot=>({slot_label:slot,state:'available'}));
 return await RMCData.rpc('get_public_day_availability',{p_date:d});
}
async function renderSlots(preserve=false){const d=dateEl.value;if(!d){slots.innerHTML='<span class="note">Choose a date to see the live schedule.</span>';timeInput.value='';return}const old=preserve?timeInput.value:'';if(!preserve)timeInput.value='';slots.innerHTML='<span class="note">Checking live availability…</span>';try{const rows=await getAvailability(d);slots.innerHTML=rows.map(r=>{const state=String(r.state||'available').toLowerCase();const label=state==='booked'?'Booked':state==='unavailable'?'Unavailable':'Available';return `<button type="button" class="time-slot ${state}${old===r.slot_label&&state==='available'?' selected':''}" data-time="${RMC.escapeHtml(r.slot_label)}" ${state!=='available'?'disabled':''}>${RMC.escapeHtml(r.slot_label)}<small>${label}</small></button>`}).join('');if(old&&rows.some(r=>r.slot_label===old&&r.state==='available'))timeInput.value=old;else if(old)timeInput.value='';slots.querySelectorAll('.time-slot.available').forEach(b=>b.onclick=()=>{slots.querySelectorAll('.time-slot').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');timeInput.value=b.dataset.time;});}catch(err){slots.innerHTML='<div class="notice">Live calendar is temporarily unavailable. Please try again.</div>';console.error(err)}}
dateEl.onchange=()=>renderSlots(false);
async function postNetlifyCopy(booking,items,total){try{document.getElementById('netlifyBookingRef').value=booking.reference;document.getElementById('netlifyServices').value=items.map(i=>`${i.name} x ${i.qty}`).join('; ');document.getElementById('netlifyEstimated').value=RMC.money(total);const fd=new FormData(form);fd.set('time',timeInput.value);const body=new URLSearchParams(fd);await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:body.toString()})}catch(e){console.warn('Netlify notification copy failed',e)}}
form.onsubmit=async e=>{e.preventDefault();setMsg('');const items=[...selected.values()];if(!items.length){setMsg('Please select at least one service.','error');return}if(!dateEl.value||!timeInput.value){setMsg('Please choose an available date and time.','error');return}if(!RMCData.configured()){setMsg('Online booking is not configured yet. Please contact Rowshan Moving Company.','error');return}const submit=form.querySelector('button[type="submit"]');submit.disabled=true;submit.textContent='Confirming live availability…';const data=Object.fromEntries(new FormData(form).entries());try{
 const result=await RMCData.rpc('create_public_booking',{p_first_name:data.firstName,p_last_name:data.lastName,p_phone:data.phone,p_email:data.email,p_service_date:data.date,p_start_slot:timeInput.value,p_origin:data.origin,p_destination:data.destination,p_details:data.details||'',p_items:items.map(i=>({service_id:i.service_id,qty:i.qty}))});
 const row=Array.isArray(result)?result[0]:result;const booking={id:row.booking_reference,reference:row.booking_reference,firstName:data.firstName,lastName:data.lastName,phone:data.phone,email:data.email,date:data.date,time:timeInput.value,origin:data.origin,destination:data.destination,items,subtotal:Number(row.subtotal),gst:Number(row.gst_amount),total:Number(row.total_estimate),status:'Confirmed'};
 sessionStorage.setItem('rmc_last_booking',JSON.stringify(booking));await postNetlifyCopy(booking,items,booking.total);location.href='booking-confirmation.html';
 }catch(err){console.error(err);const message=(err.payload?.message||err.message||'').toLowerCase();if(message.includes('slot_unavailable')||message.includes('duplicate')||message.includes('booked')){setMsg('Sorry, that time was just booked by another customer. Please select another available time.','error');await renderSlots(false)}else if(message.includes('blocked')){setMsg('That time is no longer available. Please choose another time.','error');await renderSlots(false)}else setMsg('We could not confirm the booking. Please try again or contact Rowshan Moving Company.','error');submit.disabled=false;submit.textContent='Confirm Booking · No Payment Required';}
};
(async()=>{settings=await RMC.getSettings();services=await RMC.getServices();renderServices();sync();renderSlots(false);refreshTimer=setInterval(()=>{if(dateEl.value)renderSlots(true)},30000);})();
window.addEventListener('beforeunload',()=>refreshTimer&&clearInterval(refreshTimer));
})();
