(function(){
const loginSection=document.getElementById('adminLoginSection'),dash=document.getElementById('adminDashboard'),loginForm=document.getElementById('adminLoginForm'),loginMsg=document.getElementById('loginMsg');
let token=sessionStorage.getItem('rmc_admin_token')||'',userEmail='',bookingCache=[],bookingItemCache=[],invoiceCache=[];
const esc=RMC.escapeHtml,$=id=>document.getElementById(id); const auth=()=>token;
function msg(el,t){if(el)el.textContent=t||''}
function money(n){return RMC.money(Number(n||0))}
async function verify(){if(!token)return false;try{const u=await RMCData.me(token);userEmail=u.email||'';const check=await RMCData.table.get('admin_users','select=user_id&limit=1',token);return Array.isArray(check)&&check.length>0}catch{return false}}
async function showDashboard(){loginSection.hidden=true;dash.hidden=false;$('adminIdentity').textContent=userEmail||'Rowshan Moving Company Admin';await Promise.all([loadBookings(),loadBlocks(),loadServices(),loadReviews(),loadSettings(),loadInvoices()])}
async function start(){if(!RMCData.configured()){loginMsg.textContent='Supabase must be configured in supabase-config.js before Administration can be used.';return}if(await verify())showDashboard();else{sessionStorage.removeItem('rmc_admin_token');token=''}}
loginForm.onsubmit=async e=>{e.preventDefault();msg(loginMsg,'Signing in…');try{const r=await RMCData.signIn($('adminEmail').value,$('adminPassword').value);token=r.access_token;sessionStorage.setItem('rmc_admin_token',token);if(!(await verify()))throw new Error('This account is not authorized as an Rowshan Moving Company administrator.');msg(loginMsg,'');showDashboard()}catch(err){msg(loginMsg,err.message||'Unable to sign in.');sessionStorage.removeItem('rmc_admin_token');token=''}};
$('logoutBtn').onclick=()=>{sessionStorage.removeItem('rmc_admin_token');location.reload()};
const forgotBtn=$('forgotPasswordBtn');
let resetRequestLocked=false;
if(forgotBtn)forgotBtn.onclick=async()=>{
  const email=$('adminEmail').value.trim();
  if(!email){msg(loginMsg,'Enter your administrator email first.');$('adminEmail').focus();return}
  if(resetRequestLocked){msg(loginMsg,'A reset request was just sent. Please wait a few minutes before requesting another email.');return}
  msg(loginMsg,'Sending secure password reset email…');
  forgotBtn.disabled=true;
  try{
    const redirectTo=new URL('./admin-reset.html',location.href).href;
    await RMCData.resetPassword(email,redirectTo);
    resetRequestLocked=true;
    msg(loginMsg,'Password reset email sent. Open the newest message from Supabase and follow the secure link. If it is not visible, check spam or junk mail.');
    setTimeout(()=>{resetRequestLocked=false;forgotBtn.disabled=false},120000);
  }catch(err){
    const status=Number(err&&err.status||0);
    const raw=String(err&&err.message||'');
    if(status===429 || /429|rate|too many/i.test(raw)){
      resetRequestLocked=true;
      msg(loginMsg,'Too many reset requests were made recently. Please wait a few minutes, then request one new email.');
      setTimeout(()=>{resetRequestLocked=false;forgotBtn.disabled=false},180000);
    }else{
      forgotBtn.disabled=false;
      msg(loginMsg,raw||'Unable to send password reset email.');
    }
  }
};
function openTab(name){document.querySelectorAll('.admin-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.admin-pane').forEach(x=>x.classList.remove('active'));const p=$('pane-'+name);if(p)p.classList.add('active')}
document.querySelectorAll('.admin-tab').forEach(b=>b.onclick=()=>openTab(b.dataset.tab));

async function loadBookings(){const body=$('bookingsBody');body.innerHTML='<tr><td colspan="7">Loading…</td></tr>';try{
  const rows=await RMCData.table.get('bookings','select=id,reference,first_name,last_name,phone,email,service_date,start_slot,origin,destination,details,subtotal,gst_amount,total_estimate,status,job_status,invoice_status,payment_status,created_at&order=service_date.asc,start_slot.asc',auth());
  const items=await RMCData.table.get('booking_items','select=booking_id,service_name,qty,unit_price,unit,line_total',auth());
  const invoices=await RMCData.table.get('invoices','select=id,invoice_number,booking_id,final_amount,status,issued_at,public_token&order=issued_at.desc',auth());
  bookingCache=rows; bookingItemCache=items; invoiceCache=invoices;
  const byItems={};items.forEach(i=>(byItems[i.booking_id]??=[]).push(i));const byInv=Object.fromEntries(invoices.filter(i=>i.booking_id).map(i=>[i.booking_id,i]));
  const active=rows.filter(x=>String(x.status).toLowerCase()!=='cancelled').length;$('adminStats').innerHTML=`<div><strong>${rows.length}</strong><span>Total bookings</span></div><div><strong>${active}</strong><span>Active</span></div><div><strong>${invoices.length}</strong><span>Invoices</span></div>`;
  body.innerHTML=rows.length?rows.map(b=>{const inv=byInv[b.id],sv=(byItems[b.id]||[]).map(i=>`${esc(i.service_name)} × ${i.qty}`).join('<br>');return `<tr><td><strong>${esc(b.service_date)}</strong><br>${esc(b.start_slot)}<br><small>${esc(b.reference)}</small></td><td>${esc(b.first_name)} ${esc(b.last_name)}<br><a href="tel:${esc(b.phone)}">${esc(b.phone)}</a><br><a href="mailto:${esc(b.email)}">${esc(b.email)}</a><br><small>${esc(b.origin)} → ${esc(b.destination)}</small></td><td>${sv||'—'}</td><td>${money(b.total_estimate)}</td><td><select data-booking-status="${b.id}"><option ${b.status==='Confirmed'?'selected':''}>Confirmed</option><option ${b.status==='Cancelled'?'selected':''}>Cancelled</option></select><select data-job-status="${b.id}"><option ${b.job_status==='Scheduled'?'selected':''}>Scheduled</option><option ${b.job_status==='In Progress'?'selected':''}>In Progress</option><option ${b.job_status==='Completed'?'selected':''}>Completed</option></select></td><td>${inv?`<strong>${esc(inv.invoice_number)}</strong><br>${money(inv.final_amount)}<br><small>${esc(inv.status)}</small><br><button class="small-btn" data-open-invoice="${esc(inv.public_token||'')}">Open invoice</button>`:`<button class="small-btn" data-prepare-invoice="${b.id}">Create invoice</button>`}</td><td><button class="small-btn" data-save-booking="${b.id}">Save</button></td></tr>`}).join(''):'<tr><td colspan="7">No bookings yet.</td></tr>';
  body.querySelectorAll('[data-save-booking]').forEach(btn=>btn.onclick=async()=>{const id=btn.dataset.saveBooking,status=body.querySelector(`[data-booking-status="${id}"]`).value,job_status=body.querySelector(`[data-job-status="${id}"]`).value;await RMCData.table.patch('bookings',`id=eq.${id}`,{status,job_status,updated_at:new Date().toISOString()},auth());await loadBookings();await loadBlocks()});
  body.querySelectorAll('[data-prepare-invoice]').forEach(btn=>btn.onclick=()=>prepareInvoiceFromBooking(btn.dataset.prepareInvoice));
  body.querySelectorAll('[data-open-invoice]').forEach(btn=>btn.onclick=()=>{if(!btn.dataset.openInvoice)return;window.open(publicInvoiceUrl(btn.dataset.openInvoice),'_blank')});
  populateBookingSelect();
}catch(err){console.error(err);body.innerHTML=`<tr><td colspan="7">${esc(err.message)}</td></tr>`}}
$('refreshBookings').onclick=async()=>{await loadBookings();await loadInvoices()};

async function loadBlocks(){const el=$('blockedList');try{const rows=await RMCData.table.get('availability_blocks','select=id,block_date,start_slot,reason,active&active=eq.true&order=block_date.asc,start_slot.asc',auth());el.innerHTML=rows.length?rows.map(x=>`<div class="admin-item"><div><strong>${esc(x.block_date)} · ${esc(x.start_slot||'Entire day')}</strong><small>${esc(x.reason||'Unavailable')}</small></div><button class="small-btn" data-unblock="${x.id}">Remove</button></div>`).join(''):'<p class="note">No manual blocks.</p>';el.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=async()=>{await RMCData.table.patch('availability_blocks',`id=eq.${b.dataset.unblock}`,{active:false},auth());loadBlocks()})}catch(err){el.textContent=err.message}}
$('addBlock').onclick=async()=>{const d=$('blockDate').value;if(!d)return;await RMCData.table.post('availability_blocks',{block_date:d,start_slot:$('blockTime').value||null,reason:$('blockReason').value||null,active:true},auth());loadBlocks()};

async function loadServices(){const el=$('serviceAdmin');try{const rows=await RMCData.table.get('services','select=*&order=sort_order.asc',auth());el.innerHTML=rows.map(s=>`<div class="admin-item service-admin-item"><div class="admin-grow"><strong>${esc(s.name)}</strong><small>${esc(s.description)}</small><div class="admin-inline"><label>Price<input type="number" step="0.01" data-price="${s.id}" value="${s.price}"></label><label>Minimum<input type="number" step="0.5" data-min="${s.id}" value="${s.minimum}"></label><label><input type="checkbox" data-active="${s.id}" ${s.active?'checked':''}> Active</label></div></div><button class="small-btn" data-save-service="${s.id}">Save</button></div>`).join('');el.querySelectorAll('[data-save-service]').forEach(b=>b.onclick=async()=>{const id=b.dataset.saveService;await RMCData.table.patch('services',`id=eq.${encodeURIComponent(id)}`,{price:Number(el.querySelector(`[data-price="${id}"]`).value),minimum:Number(el.querySelector(`[data-min="${id}"]`).value),active:el.querySelector(`[data-active="${id}"]`).checked,updated_at:new Date().toISOString()},auth());b.textContent='Saved';setTimeout(()=>b.textContent='Save',1000)})}catch(err){el.textContent=err.message}}

async function loadReviews(){const el=$('reviewAdmin');try{const rows=await RMCData.table.get('reviews','select=*&order=sort_order.asc,created_at.desc',auth());el.innerHTML=rows.length?rows.map(r=>`<div class="admin-item"><div class="admin-grow"><strong>${'★'.repeat(r.rating)} · ${esc(r.author)}</strong><small>${esc(r.review_text)}</small></div><label><input type="checkbox" data-review-visible="${r.id}" ${r.visible?'checked':''}> Visible</label><button class="small-btn" data-delete-review="${r.id}">Delete</button></div>`).join(''):'<p class="note">No reviews loaded yet.</p>';el.querySelectorAll('[data-review-visible]').forEach(c=>c.onchange=()=>RMCData.table.patch('reviews',`id=eq.${c.dataset.reviewVisible}`,{visible:c.checked,updated_at:new Date().toISOString()},auth()));el.querySelectorAll('[data-delete-review]').forEach(b=>b.onclick=async()=>{await RMCData.table.del('reviews',`id=eq.${b.dataset.deleteReview}`,auth());loadReviews()})}catch(err){el.textContent=err.message}}
$('addReview').onclick=async()=>{const author=$('reviewAuthor').value.trim(),review_text=$('reviewText').value.trim();if(!author||!review_text)return;await RMCData.table.post('reviews',{author,rating:Number($('reviewRating').value),review_text,review_date:$('reviewDate').value||null,source:'Google',source_url:$('reviewUrl').value||null,visible:true},auth());$('reviewAuthor').value='';$('reviewText').value='';loadReviews()};

async function loadSettings(){try{const rows=await RMCData.table.get('settings','id=eq.1&select=*',auth()),s=rows[0];if(s){$('gstRate').value=s.gst_rate;$('businessHours').value=s.business_hours;$('invoiceGstRate').value=s.gst_rate;calcInvoice()}}catch(e){console.error(e)}}
$('saveSettings').onclick=async()=>{await RMCData.table.patch('settings','id=eq.1',{gst_rate:Number($('gstRate').value),business_hours:$('businessHours').value,updated_at:new Date().toISOString()},auth());alert('Settings saved.')};

function newInvoiceNumber(){const d=new Date(),date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('');return `RB-INV-${date}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
function today(){return new Date().toISOString().slice(0,10)}
function addInvoiceLine(item={}){const el=document.createElement('div');el.className='invoice-line-edit';el.innerHTML=`<label>Description<input class="inv-desc" value="${esc(item.description||'')}" placeholder="Moving service" required></label><label>Hours / Qty<input class="inv-qty" type="number" min="0.01" step="any" value="${Number(item.qty||1)}"></label><label>Rate<input class="inv-rate" type="number" min="0" step="0.01" value="${Number(item.unit_rate??item.unit_price??0)}"></label><label>Unit<input class="inv-unit" value="${esc(item.unit||'hour')}"></label><div class="invoice-line-total"><span>Line</span><strong class="inv-line-total">$0.00</strong></div><button type="button" class="small-btn inv-remove">Remove</button>`;el.querySelectorAll('input').forEach(i=>i.addEventListener('input',calcInvoice));el.querySelector('.inv-remove').onclick=()=>{el.remove();calcInvoice()};$('invoiceLines').appendChild(el);calcInvoice()}
function calcInvoice(){let subtotal=0;document.querySelectorAll('.invoice-line-edit').forEach(r=>{const q=Number(r.querySelector('.inv-qty').value||0),rate=Number(r.querySelector('.inv-rate').value||0),line=q*rate;subtotal+=line;r.querySelector('.inv-line-total').textContent=money(line)});const rate=Number($('invoiceGstRate').value||0),gst=subtotal*rate/100,total=subtotal+gst;$('invoiceSubtotal').textContent=money(subtotal);$('invoiceGst').textContent=money(gst);$('invoiceTotal').textContent=money(total);return{subtotal,gst_rate:rate,gst_amount:gst,total}}
function clearInvoiceForm(){ $('invoiceId').value='';$('invoiceBooking').value='';$('invoiceClientName').value='';$('invoiceClientEmail').value='';$('invoiceClientPhone').value='';$('invoiceDate').value=today();$('invoiceDueDate').value='';$('invoiceStatus').value='Draft';$('invoiceNotes').value='Thank you for choosing Rowshan Moving Company.';$('invoiceLines').innerHTML='';addInvoiceLine();msg($('invoiceFormMsg'),'') }
function populateBookingSelect(){const sel=$('invoiceBooking');if(!sel)return;const current=sel.value;sel.innerHTML='<option value="">Manual invoice / no booking</option>'+bookingCache.map(b=>`<option value="${b.id}">${esc(b.reference)} · ${esc(b.first_name)} ${esc(b.last_name)} · ${esc(b.service_date)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current}
function prepareInvoiceFromBooking(id){const b=bookingCache.find(x=>x.id===id);if(!b)return;openTab('invoices');clearInvoiceForm();$('invoiceBooking').value=id;$('invoiceClientName').value=`${b.first_name} ${b.last_name}`.trim();$('invoiceClientEmail').value=b.email||'';$('invoiceClientPhone').value=b.phone||'';$('invoiceLines').innerHTML='';const items=bookingItemCache.filter(x=>x.booking_id===id);items.forEach(i=>addInvoiceLine({description:i.service_name,qty:i.qty,unit_rate:i.unit_price,unit:i.unit}));if(!items.length)addInvoiceLine();calcInvoice();window.scrollTo({top:$('pane-invoices').offsetTop-80,behavior:'smooth'})}
$('invoiceBooking').onchange=()=>{if($('invoiceBooking').value)prepareInvoiceFromBooking($('invoiceBooking').value)};
$('addInvoiceLine').onclick=()=>addInvoiceLine();$('invoiceGstRate').oninput=calcInvoice;$('newInvoiceBtn').onclick=clearInvoiceForm;
function collectLines(){return [...document.querySelectorAll('.invoice-line-edit')].map((r,idx)=>({description:r.querySelector('.inv-desc').value.trim(),qty:Number(r.querySelector('.inv-qty').value),unit_rate:Number(r.querySelector('.inv-rate').value),unit:r.querySelector('.inv-unit').value.trim()||'unit',line_total:Number(r.querySelector('.inv-qty').value)*Number(r.querySelector('.inv-rate').value),sort_order:(idx+1)*10})).filter(x=>x.description&&x.qty>0)}
async function saveInvoice(forceStatus){const lines=collectLines(),tot=calcInvoice();if(!lines.length)throw new Error('Add at least one invoice line.');if(!$('invoiceClientName').value.trim())throw new Error('Client name is required.');if(!(tot.total>0))throw new Error('Invoice total must be greater than zero.');let id=$('invoiceId').value,status=forceStatus||$('invoiceStatus').value;const payload={booking_id:$('invoiceBooking').value||null,client_name:$('invoiceClientName').value.trim(),client_email:$('invoiceClientEmail').value.trim()||null,client_phone:$('invoiceClientPhone').value.trim()||null,invoice_date:$('invoiceDate').value||today(),due_date:$('invoiceDueDate').value||null,subtotal:Number(tot.subtotal.toFixed(2)),gst_rate:tot.gst_rate,gst_amount:Number(tot.gst_amount.toFixed(2)),total_amount:Number(tot.total.toFixed(2)),final_amount:Number(tot.total.toFixed(2)),status,note:$('invoiceNotes').value.trim()||null,updated_at:new Date().toISOString()};let invoice;
  if(id){const r=await RMCData.table.patch('invoices',`id=eq.${id}`,payload,auth());invoice=r[0];await RMCData.table.del('invoice_items',`invoice_id=eq.${id}`,auth())}
  else{payload.invoice_number=newInvoiceNumber();const r=await RMCData.table.post('invoices',payload,auth());invoice=r[0];id=invoice.id;$('invoiceId').value=id}
  await RMCData.table.post('invoice_items',lines.map(x=>({...x,invoice_id:id})),auth());
  if(payload.booking_id)await RMCData.table.patch('bookings',`id=eq.${payload.booking_id}`,{invoice_status:status,payment_status:status==='Paid'?'Paid':'Payment Pending',updated_at:new Date().toISOString()},auth());
  msg($('invoiceFormMsg'),`${invoice.invoice_number} saved successfully.`);await Promise.all([loadInvoices(),loadBookings()]);return invoice
}
$('invoiceForm').onsubmit=async e=>{e.preventDefault();try{await saveInvoice($('invoiceStatus').value==='Draft'?'Issued':$('invoiceStatus').value)}catch(err){msg($('invoiceFormMsg'),err.message)}};
$('saveDraftInvoice').onclick=async()=>{try{$('invoiceStatus').value='Draft';await saveInvoice('Draft')}catch(err){msg($('invoiceFormMsg'),err.message)}};
function publicInvoiceUrl(publicToken){const u=new URL('../../invoice.html',location.href);u.searchParams.set('token',publicToken);return u.href}
function shareText(i){return `Rowshan Moving Company invoice ${i.invoice_number} - Amount due ${money(i.total_amount||i.final_amount)}. View invoice: ${publicInvoiceUrl(i.public_token)}`}
async function copyText(text,btn){await navigator.clipboard.writeText(text);const old=btn.textContent;btn.textContent='Copied!';setTimeout(()=>btn.textContent=old,1200)}
async function editInvoice(id){try{const inv=(await RMCData.table.get('invoices',`id=eq.${id}&select=*`,auth()))[0],items=await RMCData.table.get('invoice_items',`invoice_id=eq.${id}&select=*&order=sort_order.asc,id.asc`,auth());if(!inv)return;openTab('invoices');$('invoiceId').value=inv.id;$('invoiceBooking').value=inv.booking_id||'';$('invoiceClientName').value=inv.client_name||'';$('invoiceClientEmail').value=inv.client_email||'';$('invoiceClientPhone').value=inv.client_phone||'';$('invoiceDate').value=inv.invoice_date||today();$('invoiceDueDate').value=inv.due_date||'';$('invoiceStatus').value=inv.status||'Draft';$('invoiceGstRate').value=inv.gst_rate??5;$('invoiceNotes').value=inv.note||'';$('invoiceLines').innerHTML='';items.forEach(addInvoiceLine);if(!items.length)addInvoiceLine();calcInvoice();window.scrollTo({top:$('pane-invoices').offsetTop-80,behavior:'smooth'})}catch(err){msg($('invoiceFormMsg'),err.message)}}
async function loadInvoices(){const el=$('invoiceAdminList');if(!el)return;try{const rows=await RMCData.table.get('invoices','select=id,invoice_number,booking_id,public_token,client_name,client_email,client_phone,invoice_date,due_date,total_amount,final_amount,status&order=invoice_date.desc,issued_at.desc',auth());invoiceCache=rows;el.innerHTML=rows.length?rows.map(i=>`<article class="invoice-admin-card"><div><div class="invoice-card-top"><strong>${esc(i.invoice_number)}</strong><span class="invoice-status status-${esc(String(i.status).toLowerCase().replace(/\s+/g,'-'))}">${esc(i.status)}</span></div><h3>${esc(i.client_name||'Client')}</h3><p>${esc(i.client_email||'')} ${i.client_phone?'· '+esc(i.client_phone):''}</p><div class="invoice-card-total">${money(i.total_amount||i.final_amount)}</div><small>${esc(i.invoice_date||'')}</small></div><div class="invoice-card-actions"><button class="small-btn" data-edit-invoice="${i.id}">Edit</button><button class="small-btn" data-view-invoice="${esc(i.public_token)}">View</button><button class="small-btn" data-email-invoice="${i.id}">Email</button><button class="small-btn" data-text-invoice="${i.id}">Text</button><button class="small-btn" data-copy-link="${esc(i.public_token)}">Copy link</button><button class="small-btn" data-paid-invoice="${i.id}">Mark Paid</button></div></article>`).join(''):'<p class="note">No invoices created yet.</p>';
  el.querySelectorAll('[data-edit-invoice]').forEach(b=>b.onclick=()=>editInvoice(b.dataset.editInvoice));
  el.querySelectorAll('[data-view-invoice]').forEach(b=>b.onclick=()=>window.open(publicInvoiceUrl(b.dataset.viewInvoice),'_blank'));
  el.querySelectorAll('[data-copy-link]').forEach(b=>b.onclick=()=>copyText(publicInvoiceUrl(b.dataset.copyLink),b));
  el.querySelectorAll('[data-email-invoice]').forEach(b=>b.onclick=()=>{const i=rows.find(x=>x.id===b.dataset.emailInvoice);if(!i)return;location.href=`mailto:${encodeURIComponent(i.client_email||'')}?subject=${encodeURIComponent('Rowshan Moving Company Invoice '+i.invoice_number)}&body=${encodeURIComponent(shareText(i))}`});
  el.querySelectorAll('[data-text-invoice]').forEach(b=>b.onclick=()=>{const i=rows.find(x=>x.id===b.dataset.textInvoice);if(!i)return;location.href=`sms:${encodeURIComponent(i.client_phone||'')}?&body=${encodeURIComponent(shareText(i))}`});
  el.querySelectorAll('[data-paid-invoice]').forEach(b=>b.onclick=async()=>{const i=rows.find(x=>x.id===b.dataset.paidInvoice);await RMCData.table.patch('invoices',`id=eq.${i.id}`,{status:'Paid',updated_at:new Date().toISOString()},auth());if(i.booking_id)await RMCData.table.patch('bookings',`id=eq.${i.booking_id}`,{invoice_status:'Paid',payment_status:'Paid',updated_at:new Date().toISOString()},auth());await Promise.all([loadInvoices(),loadBookings()])});
}catch(err){console.error(err);el.innerHTML=`<div class="notice"><strong>Invoice module database upgrade required.</strong><br>Run <code>supabase/invoice_upgrade.sql</code> once in Supabase SQL Editor.<br><small>${esc(err.message)}</small></div>`}}

$('exportBtn').onclick=async()=>{const rows=await RMCData.table.get('bookings','select=reference,service_date,start_slot,first_name,last_name,phone,email,origin,destination,total_estimate,status,job_status,invoice_status,payment_status&order=service_date.asc',auth());const heads=['Booking','Date','Time','First Name','Last Name','Phone','Email','Origin','Destination','Estimated Total','Booking Status','Job Status','Invoice Status','Payment Status'];const vals=rows.map(r=>[r.reference,r.service_date,r.start_slot,r.first_name,r.last_name,r.phone,r.email,r.origin,r.destination,r.total_estimate,r.status,r.job_status,r.invoice_status,r.payment_status]);const csv=[heads,...vals].map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='rowshan-moving-bookings.csv';a.click()};
clearInvoiceForm();start();
})();
